ingress:
  host: null
# image_for_db: registry.gitlab.com/pagerows/pagerows/dbplv8:12.3-2.3.15-1
# image_for_dbrest: postgrest/postgrest:v7.0.1
# image_for_db: registry.gitlab.com/pagerows/pagerows/dbivm:14
image_for_db: registry.gitlab.com/pagerows/pagerows/db:14
image_for_dbrest: postgrest/postgrest:v9.0.0.20220107

image_db_backup: registry.gitlab.com/pagerows/pagerows/db-backup:b5bdc51b-dirty@sha256:b0180c51255839678e591b097af0fbb0db71cdd9a8f80481c16be82db2704211
