# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: init-db
# spec:
#   template:
#     spec:
#       initContainers:
#       - name: check-db-ready
#         image: postgres@sha256:05580d6c8f7bb0566793c7c45ab276458c53c9c31300c046ba6fcbc66598c7b9
#         command: ['sh', '-c', 'until pg_isready -h db -p 5432 -t 1; do echo waiting for database; sleep 2; done;']
#       containers:
#       - name: psql
#         image: bitnami/kubectl:1.17.13
#         command: ["kubectl", "-n", "{{ .Release.Namespace }}", "exec", "db-0", "--", "sh", "-c", "set -ex; for i in /migrations/*.sql; do PGPASSWORD=postgres psql -v ON_ERROR_STOP=1 -e -h ${PGHOST:-db} -U postgres -f $i; done"]
#       restartPolicy: Never
#   backoffLimit: 4
