apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  serviceName: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - name: db
        image: {{ .Values.image_for_db }}
        imagePullPolicy: IfNotPresent
        command: ["docker-entrypoint.sh", "-c", "log_statement=all"]
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-persistence
          subPath: postgres
      - name: dbrest
        image: postgrest/postgrest:v7.0.1
        ports:
        - containerPort: 3000
        env:
        - { name: PGRST_DB_URI, value: 'postgres://postgres:postgres@localhost:5432' }
        - { name: PGRST_DB_ANON_ROLE, value: 'frmdb_anon' }
        - { name: PGRST_JWT_SECRET, value: 'asd1238d140dhoicoiqhewodqhed81-312d' }
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: pg-persistence
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi
