apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/pagerows/pagerows/rows
    context: .
    sync:
      infer: ['pg/**', 'scripts/**', 'src/**']
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: pagerows-rows
      chartPath: ./helm
      artifactOverrides:
        image_rows: registry.gitlab.com/pagerows/pagerows/rows
      setValueTemplates: 
        #ingress.host: "{{ .PRW_INGRESS_HOST }}"
        envtype: localdev
      namespace: prw
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValueTemplates/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
