apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/pagerows/pagerows/rows
    context: .
    sync:
      infer: ['core/**']
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: pagerows-rows
      chartPath: ./helm
      artifactOverrides:
        image_resources: registry.gitlab.com/pagerows/pagerows/rows
      setValues: 
        ingress.host: frmdb.localhost
        envtype: localdev
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValues/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
