variables:
  GIT_DEPTH: 5
default:
  image: node

stages:
  - build_pages
  - test_pages

build_pages:
  stage: build_pages
  script:
    - cd pages
    - npm install
    - npm run build

test_pages:
  stage: test_pages
  script:
    - npm test
