variables:
  GIT_DEPTH: 5
default:
  image: node:lts-alpine3.12
  before_script:
    - apk add --no-cache bash git make gcc g++ python3

stages:
  - build_pages
  - test_pages

build_pages:
  stage: build_pages
  script:
    - cd pages
    - npm install
    - npm run build

test_pages:
  stage: test_pages
  script:
    - npm test
