variables:
  GIT_DEPTH: 5
default:
  image: node:lts-alpine3.12
  before_script:
    - apk add --no-cache bash git make gcc g++ python3

include:
- local: './pages/.gitlab-ci.yml'
- local: './rows/.gitlab-ci.yml'
- local: './obj/.gitlab-ci.yml'
- local: './db/.gitlab-ci.yml'
