variables:
  GIT_DEPTH: 5
default:
  image: node

stages:
  - build_pages
  - test_pages

build_page:
  stage: build_page
  script:
    - npm install
    - npm run build

test_pages:
  state: test_pages
  script:
    - npm test
