variables:
  GIT_DEPTH: 5
default:
  image: node:lts-alpine3.12
  before_script:
    - apk add --no-cache bash git make gcc g++ python3

stages:
  - install
  - build
  - test

install_pages:
  stage: install
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/

build_pages:
  stage: build
  script:
    - cd pages
    - npm install
    - npm run build

test_pages:
  stage: test
  script:
    - npm test
