variables:
  GIT_DEPTH: 5
default:
  image: node

stages:
  script:
    - build_pages
    - test_pages

build_page:
  script:
    - npm install
    - npm run build

test_pages:
  script:
    - npm test
