# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: pagerows-db
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /dbweb(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: db
#             port:
#               number: 8081
#     {{ if .Values.ingress.host}}host: {{ .Values.ingress.host }}{{end}}
