apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  - name: "dbrest"
    port: 3000
    targetPort: 3000
  # - name: "dbweb"
  #   port: 8081
  #   targetPort: 8081
  selector:
    service: db
status:
  loadBalancer: {}
