apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
spec:
  replicas: 1
  selector:
    matchLabels:
      service: resources
  strategy: {}
  template:
    metadata:
      labels:
        service: resources
    spec:
      containers:
      - name: resources
        image: {{ .Values.image_resources }}
        ports:
        - containerPort: 8080
        env:
        - { name: MINIO_ACCESS_KEY, value: "2VTDNqA7p9wlkNFgxB" }
        - { name: MINIO_SECRET_KEY, value: "S8wavKlP7DRTo5hXyEsBaCVjpW5qEs0dvcUDlOBcaFJdSSS3zILfoK9rXjfBGlVn" }
        #FIXME: replace with k8s secret
        - { name: JWT_SECRET, value: "asd1238d140dhoicoiqhewodqhed81-312d" }
      imagePullSecrets:
        - name: regcred
