apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formuladb-resources
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /formuladb-resources(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: resources
            port:
              number: 8080  
    {{ if .Values.ingress.host}}host: {{ .Release.Namespace }}.{{ .Values.ingress.host }}{{end}}
