apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pagerows-pages
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: pages
            port: 
              number: 3000              
    {{ if .Values.ingress.host}}host: {{ .Values.ingress.host }}{{end}}

