import { CPageNode } from '@core/entity/page';

export const isf__id: CPageNode = {
    "_tag": "CPage",
    "_id": "ROOT",
    "cPageType": "Edit",
    "children": [
        {
            "_tag": "CForm",
            "_id": "Ek4N5ig9v",
            "resource": "isf",
            "children": [
                {
                    "_tag": "CLayout",
                    "_id": "Row1",
                    spacing: 3,
                    "children": [
                        {
                            "_tag": "CBlock",
                            "_id": "jW9ZraEAL2",
                            "cBlockType": "Heading",
                            "title": "Hai pe harta fotbalului românesc!",
                            "subtitle": "Ia-ți 5 minute, completează formularul și noi te punem pe hartă.",
                            body: "Te rugăm să completezi cu atenție fiecare câmp pentru a oferi informații corecte celor care vor să afle mai multe despre clubul tău.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "3Ubid",
                            "cElementType": "Text",
                            "content": "Câmpurile marcate cu * sunt obligatorii.",
                            item: { width: 12 },
                        },
                    ]
                },
                {
                    "_tag": "CLayout",
                    "_id": "Row2",
                    spacing: 3,
                    "children": [
                        {
                            "_tag": "CElement",
                            "_id": "t2.1",
                            "cElementType": "Text",
                            "content": "Date despre persoana care completează formularul.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t2.2",
                            "cElementType": "Text",
                            "content": "Aceste date nu vor fi făcute publice și sunt colectate strict pentru a facilita legătura între FRF și persoana respectivă.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic2.1",
                            "cElementType": "Icon",
                            name: "material-design-icons-account_circle",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in2.1",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "nume",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic2.2",
                            "cElementType": "Icon",
                            name: "material-design-icons-account_circle",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in2.2",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "prenume",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic2.3",
                            "cElementType": "Icon",
                            name: "material-design-icons-phone",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in2.3",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "telefon",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic2.4",
                            "cElementType": "Icon",
                            name: "material-design-icons-email",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in2.4",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "email",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 5 },
                        },
                    ]
                },
                {
                    "_tag": "CLayout",
                    "_id": "Row3",
                    spacing: 3,
                    box: {
                        spacing: {
                            paddingTop: 5,
                        }
                    },
                    "children": [
                        {
                            "_tag": "CElement",
                            "_id": "t3.2",
                            "cElementType": "Text",
                            "content": "DATE despre clubul pe care il reprezinti.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.3",
                            "cElementType": "Text",
                            "content": "Răspunsurile de la întrebările 1,2,3,4,5,6,9,10,11,12,13,14,15,16,17,18,19,20,21 vor fi făcute publice pentru a crește expunerea clubului tău. Excepție fac datele introduse la întrebările 7 și 8, pentru care îți oferim opțiunea de a nu le face publice în cazul în care nu dorești acest lucru.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4",
                            "cElementType": "Text",
                            "content": "1) Care este județul de care aparține clubul tău? *",
                            item: { width: 4 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.5",
                            "cElementType": "Text",
                            "content": " ",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in3.1",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "judet_club",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.6",
                            "cElementType": "Text",
                            "content": "2) Din ce localitate provine clubul tău? *",
                            item: { width: 4 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.7",
                            "cElementType": "Text",
                            "content": " ",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in3.2",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "localitate_club",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.3.1",
                            "cElementType": "Text",
                            "content": "3) Care este denumirea completă a clubului tău? : *",
                            item: { width: 4 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic3.3",
                            "cElementType": "Icon",
                            "name": "material-design-icons-sports_soccer",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in3.3",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "denumire_club",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.1",
                            "cElementType": "Text",
                            "content": "4) Care este numărul de identificare sportivă a clubului tău - CIS (din Certificatul de identitate sportivă)? : *",
                            item: { width: 4 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "ic3.4",
                            "cElementType": "Icon",
                            "name": "material-design-icons-code",
                            item: { width: 1 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in3.4",
                            "cInputType": "TextField",
                            "resource": "isf",
                            "source": "nr_identificare_club",
                            "variant": "standard",
                            "disabled": false,
                            item: { width: 7 },
                        },
                    ]
                },
                {
                    "_tag": "CLayout",
                    "_id": "Row4",
                    spacing: 3,
                    box: {
                        spacing: {
                            marginTop: 5,
                        },
                        borders: {
                            borderTop: 1,
                        }
                    },
                    "children": [
                        {
                            "_tag": "CElement",
                            "_id": "t4.1",
                            "cElementType": "Text",
                            "content": "10) Adaugă fișierul logo și maxim 5 fotografii reprezentative pentru club.",
                            item: { width: 12 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.2",
                            "cElementType": "Text",
                            "content": "Încarcă fișierul logo club aici:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.1",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "logo",
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.3",
                            "cElementType": "Text",
                            "content": "Fotografie 1:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.2",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "imagine1",
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.4",
                            "cElementType": "Text",
                            "content": "Fotografie 2:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.4",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "imagine2",
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.5",
                            "cElementType": "Text",
                            "content": "Fotografie 3:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.5",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "imagine3",
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.6",
                            "cElementType": "Text",
                            "content": "Fotografie 4:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.6",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "imagine4",
                            item: { width: 7 },
                        },
                        {
                            "_tag": "CElement",
                            "_id": "t3.4.7",
                            "cElementType": "Text",
                            "content": "Fotografie 5:",
                            item: { width: 5 },
                        },
                        {
                            "_tag": "CInput",
                            "_id": "in4.7",
                            "cInputType": "ImageField",
                            "resource": "isf",
                            "source": "imagine5",
                            item: { width: 7 },
                        },
                    ]
                },
                {
                    "_tag": "CList",
                    "_id": "lUQUqX",
                    "cListType": "Table",
                    "resource": "playfield",
                    "labelSource": "id",
                    "editable": false,
                    "refToParentListFieldName": "isf_id",
                    "isSubListOf": "isf",
                    "enabledActions": [
                        {
                            "actionType": "CREATE"
                        }
                    ],
                    fields: [
                        { cInputType: 'TextField', source: "nume", resource: 'playfield' },
                        { cInputType: 'TextField', source: "localitate", resource: 'playfield' },
                        { cInputType: 'TextField', source: "strada", resource: 'playfield' },
                        { cInputType: 'NumberField', source: "nr_teren", resource: 'playfield' },
                        { cInputType: 'TextField', source: "cod_postal", resource: 'playfield' },
                    ]
                },
            ]
        }
    ]
}