apiVersion: skaffold/v2beta11
kind: Config
build:
  local:
    concurrency: 0 #builds all artifacts parallely
requires:
  - path: ../db
    activeProfiles:
      - { name: localdev, activatedBy: [localdev] }
      - { name: production, activatedBy: [production] }
  - path: ../pages
    activeProfiles:
      - { name: localdev, activatedBy: [localdev] }
      - { name: production, activatedBy: [production] }
  - path: ../rows
    activeProfiles:
      - { name: localdev, activatedBy: [localdev] }
      - { name: production, activatedBy: [production] }
profiles:
  - name: localdev
  - name: production
