apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pagerows-obj
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /minio
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio
            port:
              number: 9000  
      - path: /frmdb-bucket
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio
            port:
              number: 9000  
    {{ if .Values.ingress.host}}host: {{ .Release.Namespace }}.{{ .Values.ingress.host }}{{end}}
