apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formuladb-dbweb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Script-Name /formuladb-dbweb;
spec:
  rules:
  - http:
      paths:
      - path: /fdb-dbweb(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dbweb
            port:
              number: 80  
    {{ if .Values.ingress.host}}host: {{ .Release.Namespace }}.{{ .Values.ingress.host }}{{end}}
