apiVersion: skaffold/v2beta11
kind: Config
deploy:
  helm:
    releases:
    - name: pagerows-obj
      chartPath: ./helm
      setValueTemplates: 
        ingress.host: "{{ .PRW_INGRESS_HOST }}"
        envtype: localdev
      namespace: "{{ .PRW_NAMESPACE }}"
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValueTemplates/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
