apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  # - image: registry.gitlab.com/pagerows/pagerows/db-backup
  #   context: backup
  #   docker:
  #     dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: pagerows-db
      chartPath: ./helm
      # artifactOverrides:
      #   image_db_backup: registry.gitlab.com/pagerows/pagerows/db-backup
      setValues: 
        ingress.host: frmdb.localhost
        envtype: localdev
      #namespace: "{{ .PRW_NAMESPACE }}"
      namespace: prw
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValues/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
