apiVersion: skaffold/v2beta11
kind: Config
deploy:
  helm:
    releases:
    - name: pagerows-db
      chartPath: ./helm
      setValues: 
        ingress.host: frmdb.localhost
        envtype: localdev
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValues/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
