FROM node:lts-alpine

RUN apk add --no-cache git curl less

COPY package.json /package.json
# COPY package-lock.json /package-lock.json
RUN npm install --unsafe-perm

ADD . /
RUN find /src -name \*.ts | xargs sed -ie 's!from "typeorm"!from "typeorm/typeorm-model-shim"!g'
CMD npm start
