apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/pagerows/pagerows/pages
    context: .
    sync:
      manual:
      - src: '**/*'
        dest: /
    docker:
      dockerfile: Dockerfile.dev
deploy:
  helm:
    releases:
    - name: pagerows-pages
      chartPath: ./helm
      artifactOverrides:
        image_pages: registry.gitlab.com/pagerows/pagerows/pages
      setValues: 
        ingress.host: frmdb.localhost
        envtype: localdev
      namespace: "{{ .NAMESPACE }}"
      createNamespace: true
profiles:
- name: localdev
- name: production
  patches:
  - op: replace
    path: /deploy/helm/releases/0/setValues/envtype
    value: production
  # - op: remove
  #   path: /build/cluster
  # - op: remove
  #   path: /build/artifacts/0/docker
  # - op: add
  #   path: /build/artifacts/0/kaniko
  #   value:
  #     dockerfile: Dockerfile
